remote_theme: zendesk/jekyll-theme-zendesk-garden@main
plugins:
- jekyll-remote-theme
title: Blasphemous Randomizer Wiki
tagline: Information related to the Blasphemous Randomizer
description: Wiki information for the Blasphemous Randomizer

version: false
search_enabled: true

sidebar:
  - Home
  - label: The Holy Line
    children:
      - D01Z01S01
      - D01Z01S02
      - D01Z01S03
      - D01Z01S07
  - Ending