remote_theme: zendesk/jekyll-theme-zendesk-garden@main
plugins:
- jekyll-remote-theme
title: Blasphemous Randomizer Wiki
tagline: Information related to the Blasphemous Randomizer
description: Wiki information for the Blasphemous Randomizer